### PR TITLE
Replace "spermic" adjective with "aubergine"

### PR DESCRIPTION
**Pull request by alexanderreiff**
As in the color, not the fruit

### CODE REVIEW

**Review by bringking — APPROVED** [review]
You are now spermicide

**Review by choubacha — APPROVED** [review]

**Comment by alexanderreiff** [comment]
@kbacha I think we need to switch the CI on this repo away from Circle or switch to a free account?

**Comment by choubacha** [comment]
I think it doesn't build on forks... I will investigate @alexanderreiff

**Comment by choubacha** [comment]
Gonna merge, should build next time though!

**Comment by alexanderreiff** [comment]
Thanks!

**Pull request merged**
